lib: work around unnamed structs/unions
Exported header files used by applications should allow the strictest
compiler flags. Language extensions used in many places must be explicitly
marked to avoid warnings and compilation failures.

Unnamed structs/unions are allowed since C11, however many compiler
versions do not use this mode by default.

This commit prevents the following errors:

 error: ISO C99 doesn't support unnamed structs/unions
 error: struct has no named members

Signed-off-by: Adrien Mazarguil <adrien.mazarguil@6wind.com>
(cherry picked from commit f9e97a98efb4f0e7fe799cf37ca73381148d99d6)
Signed-off-by: Adrien Mazarguil <adrien.mazarguil@6wind.com>

Conflicts:
	lib/librte_cryptodev/rte_crypto.h
	lib/librte_cryptodev/rte_crypto_sym.h
	lib/librte_cryptodev/rte_cryptodev.h
	lib/librte_lpm/rte_lpm.h
	lib/librte_mempool/rte_mempool.h