mlx5: work around spurious compilation errors
Since commit "mlx5: resurrect TX gather support", older GCC versions (such
as 4.8.5) may complain about the following:

 mlx5_rxtx.c: In function ‘mlx5_tx_burst’:
 mlx5_rxtx.c:705:25: error: ‘wqe’ may be used uninitialized in this function
     [-Werror=maybe-uninitialized]

 mlx5_rxtx.c: In function ‘mlx5_tx_burst_inline’:
 mlx5_rxtx.c:864:25: error: ‘wqe’ may be used uninitialized in this function
     [-Werror=maybe-uninitialized]

In both cases, this code cannot be reached when wqe is not initialized.

Considering older GCC versions are still widely used, work around this issue
by initializing wqe preemptively, even if it should not be necessary.

Signed-off-by: Adrien Mazarguil <adrien.mazarguil@6wind.com>