remove extra parentheses in return statement
fix the error reported by checkpatch:
  "ERROR: return is not a function, parentheses are not required"

remove parentheses in return like:
  "return (logical expressions)"

remove parentheses in return a function like:
  "return (rte_mempool_lookup(...))"

Fixes: 6307b909b8e0 ("lib: remove extra parenthesis after return")

Signed-off-by: Huawei Xie <huawei.xie@intel.com>
(cherry picked from commit 693f715da45c48ec1ec0fe4ba2f3b5ffd11ba53e)

AM: only kept the part affecting Mellanox PMDs.

Signed-off-by: Adrien Mazarguil <adrien.mazarguil@6wind.com>

Conflicts:
	drivers/net/virtio/virtio_pci.c