net/mlx5: fix compilation errors
The folowing errors occur in debugging mode:

 mlx5_rxtx.h:247:2: error: type of bit-field 'elts_n' is a GCC extension
  [-Werror=pedantic]
 mlx5_rxtx.h:248:2: error: type of bit-field 'cqe_n' is a GCC extension
  [-Werror=pedantic]
 mlx5_rxtx.h:249:2: error: type of bit-field 'wqe_n' is a GCC extension
  [-Werror=pedantic]
 mlx5_rxtx.h:250:2: error: type of bit-field 'bf_buf_size' is a GCC
  extension [-Werror=pedantic]

Fixes: b583216112da ("net/mlx5: store number of elements in log2 format")

Signed-off-by: Adrien Mazarguil <adrien.mazarguil@6wind.com>
(cherry picked from commit 443cdc5158fa9d0cf5a02c970f266740667fd0f2)
Signed-off-by: Adrien Mazarguil <adrien.mazarguil@6wind.com>