lib: work around structs with no members
Exported header files used by applications should allow the strictest
compiler flags. Language extensions used in many places must be explicitly
marked or removed to avoid warnings and compilation failures.

This commit prevents the following errors:

 error: struct has no members

Signed-off-by: Adrien Mazarguil <adrien.mazarguil@6wind.com>
(cherry picked from commit a68a1fffb450418238169ee6881fc77670e27f25)
Signed-off-by: Adrien Mazarguil <adrien.mazarguil@6wind.com>