lib: add missing include dependencies
Exported header files for use by applications should be self sufficient and
allow out of order inclusion. Moreover, they must include all the system
headers they need for types and macros.

This commit prevents the following errors:

 error: `RTE_MAX_LCORE' undeclared here (not in a function)
 error: `RTE_LPM_VALID_EXT_ENTRY_BITMASK' undeclared
  (first use in this function)
 error: #error "Unsupported cache line size"
 error: `asm' undeclared (first use in this function)
 error: implicit declaration of function `[...]'
 error: unknown type name `[...]'
 error: field `mac_addr' has incomplete type
 error: `CHAR_BIT' undeclared here (not in a function)
 error: `struct [...]' declared inside parameter list
 error: unknown type name `uint8_t'

Signed-off-by: Adrien Mazarguil <adrien.mazarguil@6wind.com>
(cherry picked from commit 0f08eabd979a9d1fb7604fd99399f80c4fca7fc5)
Signed-off-by: Adrien Mazarguil <adrien.mazarguil@6wind.com>

Conflicts:
	lib/librte_cmdline/cmdline_parse_portlist.h
	lib/librte_lpm/rte_lpm_neon.h
	lib/librte_lpm/rte_lpm_sse.h
	lib/librte_pdump/rte_pdump.h
	lib/librte_sched/rte_reciprocal.h