lib: use C99 syntax for zero-size arrays
Exported header files used by applications should allow the strictest
compiler flags. Language extensions used in many places must be explicitly
marked or removed to avoid warnings and compilation failures.

The extension keyword is used whenever the C99 syntax cannot do it.

This commit prevents the following errors:

 error: ISO C forbids zero-size array `[...]'

Signed-off-by: Adrien Mazarguil <adrien.mazarguil@6wind.com>
(cherry picked from commit e69ee08b4f200dd1c660846b2a9ff056447c0ca0)
Signed-off-by: Adrien Mazarguil <adrien.mazarguil@6wind.com>

Conflicts:
	lib/librte_cryptodev/rte_cryptodev.h
	lib/librte_lpm/rte_lpm.h